package com.bluebellcspl.maarevacommoditytradingapp.model

data class APMCMasterModelItem(
    var APMCId: String,
    var APMCName: String,
    var BankFacility: String,
    var ChairmanName: String,
    var CompanyCode: String,
    var CreateDate: String,
    var CreateUser: String,
    var DistrictId: String,
    var DistrictName: String,
    var EDate: String,
    var EstabishmentDetails: String,
    var EstablishmentDate: String,
    var InfrastructureFacility: String,
    var IsActive: String,
    var LaboratoryFacility: String,
    var Location: String,
    var NoOfBoardMember: String,
    var NoOfEmployee: String,
    var NoOfShop: String,
    var NoOfTraders: String,
    var SecretaryName: String,
    var SrNo: String,
    var StateId: String,
    var StateName: String,
    var UpdateDate: String,
    var UpdateUser: String,
    var WarehouseFacility: String,
    var WeightbridgeFacility: String,
    var WiseChairman: String
)