package com.bluebellcspl.maarevacommoditytradingapp.model

data class AuctionDetailsModel(
    var APMCId: String,
    var APMCName: String,
    var Amount: String,
    var AuctionMasterId: String,
    var Bags: String,
    var BuyerCityId: String,
    var CommodityId: String,
    var DetailsId: String,
    var DistrictId: String,
    var GCACommCharge: String,
    var GCACommRate: String,
    var LowerLimit: String,
    var MarketCessCharge: String,
    var MarketCessRate: String,
    var PCACityId: String,
    var PCACommCharge: String,
    var PCACommRate: String,
    var PCAId: String,
    var PCALowerLimit: String,
    var PCAName: String,
    var PCAShortName: String,
    var GujaratiPCAShortName: String,
    var PCARegId: String,
    var PCAUpperLimit: String,
    var PerBoriRate: String,
    var StateId: String,
    var TransportId: String,
    var TransportationCharge: String,
    var UpdGCACommRate: String,
    var UpdLabourCharge: String,
    var UpdMarketCessRate: String,
    var UpdPCACommRate: String,
    var UpdPerBoriRate: String,
    var UpdTransportId: String,
    var UpperLimit: String,
    var LabourCharge: String?,
    var PerBoriLabourCharge: String,
    var Basic:String
)