package com.bluebellcspl.maarevacommoditytradingapp.model

data class BuyerMasterModelItem(
    var AdharCardImage: String,
    var AdharCardNo: String,
    var BuyerId: String,
    var BuyerRegId: String,
    var CityId: String,
    var CityName: String,
    var CommodityId: String,
    var CommodityName: String,
    var CompanyCode: String,
    var CreateDate: String,
    var CreateUser: String,
    var Email: String,
    var GSTCertiImage: String,
    var GSTNo: String,
    var IsActive: String,
    var IsApprove: String,
    var MobileNo: String,
    var MobileNo2: String,
    var Name: String,
    var OfficeAddress: String,
    var PanCardImage: String,
    var PanCardNo: String,
    var ProfileImage: String,
    var ResidenceAddress: String,
    var RoleId: String,
    var RoleName: String,
    var UpdateDate: String,
    var UpdateUser: String,
    var cdate: String,
    var udate: String
)