package com.bluebellcspl.maarevacommoditytradingapp.model

data class IndPCAInvoicePreviewModel(
    var Bharti: String,
    var BuyerAddress: String,
    var BuyerCity: String,
    var BuyerCityName: String,
    var BuyerCityNamefromCityMaster: String,
    var BuyerFullName: String,
    var BuyerGSTNo: String,
    var BuyerId: String,
    var BuyerPanNo: String,
    var BuyerShortName: String,
    var CGST: String,
    var CommodityId: String,
    var CompanyCode: String,
    var FinanceYear: String,
    var GSTTotalPct: String,
    var GstId: String,
    var HSNASC: String,
    var InvoiceDate: String,
    var LabourCharges: String,
    var MarketCess: String,
    var PCAAddress: String,
    var PCACity: String,
    var PCACityId: String,
    var PCACommodityName: String,
    var PCAGSTNo: String,
    var PCAId: String,
    var PCAMobileNo: String,
    var PCAName: String,
    var PCAPanNo: String,
    var PCARegId: String,
    var PCApcaCommissiom: String,
    var PerBoriRate: String = "",
    var PreviewBankListTable: ArrayList<PreviewBankTable>,
    var SGST: String,
    var StateId: String,
    var StateName: String
)