package com.bluebellcspl.maarevacommoditytradingapp.model

data class InvoicePreviewModel(
    var Bharti: String,
    var BuyerAddress: String,
    var BuyerCity: String,
    var BuyerGSTNo: String,
    var BuyerId: String,
    var BuyerName: String,
    var BuyerPanNo: String,
    var CommodityId: String,
    var CompanyCode: String,
    var FinanceYear: String,
    var GSTTotalPct: String,
    var GstId: String,
    var InvoiceDate: String,
    var LabourCharges: String,
    var MarketCess: String,
    var PCAAddress: String,
    var PCACity: String,
    var PCACommodityName: String,
    var PCAGSTNo: String,
    var PCAId: String,
    var PCAMobileNo: String,
    var PCAName: String,
    var PCAPanNo: String,
    var PCARegId: String,
    var PCAgcaCommissiom: String,
    var PCApcaCommissiom: String,
    var PerBoriRate: String,
    var PreviewBankListTable: ArrayList<PreviewBankTable>,
    var StateId: String,
    var StateName: String
)