package com.bluebellcspl.maarevacommoditytradingapp.model

data class PostInvoiceDataModel(
    var Action: String,
    var BuyerAddress: String,
    var BuyerCity: String,
    var BuyerGstIn: String,
    var BuyerId: String,
    var BuyerName: String,
    var BuyerPanNo: String,
    var CompanyCode: String,
    var CreateUser: String,
    var Date: String,
    var FinalAmount: String,
    var FinalAmountWord: String,
    var FinalCGSTAmount: String,
    var FinalCGSTPct: String,
    var FinalGCACommission: String,
    var FinalGCARate: String,
    var FinalGSTAmount: String,
    var FinalGSTPct: String,
    var FinalLabourCharge: String,
    var FinalLabourRate: String,
    var FinalMarketFee: String,
    var FinalMarketRate: String,
    var FinalPCACommission: String,
    var FinalPCARate: String,
    var FinalSGSTAmount: String,
    var FinalSGSTPct: String,
    var FinalTransportCharge: String,
    var FinalTransportRate: String,
    var FinanceYear: String,
    var InvoiceDetailsModel: ArrayList<InvoiceDetailsModel>,
    var PCAId: String,
    var PCARegId: String,
    var UpdateUser: String,
    var VechicalNo: String
)